### ISSUE TITLE
update to node20

### ISSUE THREAD

**Issue by AlexisColes** [thiagodnf/yaml-schema-checker#14]
Hi,

node16 is now deprecated, please could you update this action to use node20

Thanks

created this PR if it helps https://github.com/thiagodnf/yaml-schema-checker/pull/15/files

**Comment by EugeneBalybin** [comment]
Are there any plans for that? @thiagodnf

**Comment by thiagodnf** [comment]
Sure. Would you mind if I ask to test the version 0.0.12? @EugeneBalybin
